import 'package:hive_flutter/hive_flutter.dart';
import 'package:efoy/models/patient.dart';
import 'package:efoy/models/queue_entry.dart';
import 'package:efoy/models/instruction.dart';
import 'package:efoy/models/navigation_step.dart';
import 'package:efoy/models/pain_report.dart';
import 'package:efoy/models/feedback.dart' as efoy;

class HiveService {
  static const String _patientBox = 'patients';
  static const String _queueBox = 'queue';
  static const String _instructionBox = 'instructions';
  static const String _navigationBox = 'navigation';
  static const String _smsHistoryBox = 'sms_history';
  static const String _settingsBox = 'settings';
  
  static Future<void> init() async {
    // Register adapters (will be generated by build_runner)
    // Run: flutter pub run build_runner build
    try {
      if (!Hive.isAdapterRegistered(0)) {
        // PatientAdapter will be generated
        // Hive.registerAdapter(PatientAdapter());
      }
      if (!Hive.isAdapterRegistered(1)) {
        // QueueEntryAdapter will be generated
        // Hive.registerAdapter(QueueEntryAdapter());
      }
      if (!Hive.isAdapterRegistered(2)) {
        // InstructionTypeAdapter will be generated
        // Hive.registerAdapter(InstructionTypeAdapter());
      }
      if (!Hive.isAdapterRegistered(3)) {
        // InstructionAdapter will be generated
        // Hive.registerAdapter(InstructionAdapter());
      }
      if (!Hive.isAdapterRegistered(4)) {
        // NavigationStepAdapter will be generated
        // Hive.registerAdapter(NavigationStepAdapter());
      }
    } catch (e) {
      print('Note: Hive adapters not yet generated. Run: flutter pub run build_runner build');
    }
    
    // Open boxes (using generic boxes for now)
    await Hive.openBox(_patientBox);
    await Hive.openBox(_queueBox);
    await Hive.openBox(_instructionBox);
    await Hive.openBox(_navigationBox);
    await Hive.openBox(_smsHistoryBox);
    await Hive.openBox(_settingsBox);
    await Hive.openBox('pain_reports');
    await Hive.openBox('feedback');
  }
  
  // Patient operations
  static Future<void> savePatient(Patient patient) async {
    final box = Hive.box(_patientBox);
    await box.put(patient.id, patient.toJson());
  }
  
  static Patient? getPatient(String patientId) {
    final box = Hive.box(_patientBox);
    final data = box.get(patientId);
    if (data == null) return null;
    try {
      return Patient.fromJson(Map<String, dynamic>.from(data));
    } catch (e) {
      return null;
    }
  }
  
  static Patient? getCurrentPatient() {
    final box = Hive.box(_settingsBox);
    final patientId = box.get('current_patient_id') as String?;
    if (patientId == null) return null;
    return getPatient(patientId);
  }

  static List<Patient> getAllPatients() {
    final box = Hive.box(_patientBox);
    return box.values
        .map((data) {
          try {
            return Patient.fromJson(Map<String, dynamic>.from(data));
          } catch (e) {
            return null;
          }
        })
        .whereType<Patient>()
        .toList();
  }
  
  static Future<void> setCurrentPatient(String patientId) async {
    final box = Hive.box(_settingsBox);
    await box.put('current_patient_id', patientId);
  }
  
  static Future<void> clearCurrentPatient() async {
    final box = Hive.box(_settingsBox);
    await box.delete('current_patient_id');
  }
  
  // Queue operations
  static Future<void> saveQueueEntry(QueueEntry entry) async {
    final box = Hive.box(_queueBox);
    await box.put(entry.id, entry.toJson());
  }
  
  static QueueEntry? getQueueEntry(String entryId) {
    final box = Hive.box(_queueBox);
    final data = box.get(entryId);
    if (data == null) return null;
    try {
      return QueueEntry.fromJson(Map<String, dynamic>.from(data));
    } catch (e) {
      return null;
    }
  }
  
  static List<QueueEntry> getAllQueueEntries() {
    final box = Hive.box(_queueBox);
    return box.values
        .map((data) {
          try {
            return QueueEntry.fromJson(Map<String, dynamic>.from(data));
          } catch (e) {
            return null;
          }
        })
        .whereType<QueueEntry>()
        .toList();
  }
  
  // Instruction operations
  static Future<void> saveInstruction(Instruction instruction) async {
    final box = Hive.box(_instructionBox);
    await box.put(instruction.id, instruction.toJson());
  }
  
  static List<Instruction> getPatientInstructions(String patientId) {
    final box = Hive.box(_instructionBox);
    return box.values
        .map((data) {
          try {
            final inst = Instruction.fromJson(Map<String, dynamic>.from(data));
            return inst.patientId == patientId ? inst : null;
          } catch (e) {
            return null;
          }
        })
        .whereType<Instruction>()
        .toList();
  }
  
  // Navigation operations
  static Future<void> saveNavigationStep(NavigationStep step) async {
    final box = Hive.box(_navigationBox);
    await box.put(step.id, step.toJson());
  }
  
  static NavigationStep? getActiveNavigationStep(String patientId) {
    final box = Hive.box(_navigationBox);
    try {
      return box.values
          .map((data) {
            try {
              return NavigationStep.fromJson(Map<String, dynamic>.from(data));
            } catch (e) {
              return null;
            }
          })
          .whereType<NavigationStep>()
          .where((n) => n.patientId == patientId && !n.isCompleted)
          .firstOrNull;
    } catch (e) {
      return null;
    }
  }
  
  // SMS history
  static Future<void> saveSMSToHistory(String phone, String message) async {
    final box = Hive.box(_smsHistoryBox);
    final history = box.get('history', defaultValue: <Map<String, dynamic>>[]) as List;
    history.add({
      'phone': phone,
      'message': message,
      'timestamp': DateTime.now().toIso8601String(),
    });
    await box.put('history', history);
  }
  
  // Settings
  static Future<void> setLanguage(String languageCode) async {
    final box = Hive.box(_settingsBox);
    await box.put('language', languageCode);
  }
  
  static String getLanguage() {
    final box = Hive.box(_settingsBox);
    return box.get('language', defaultValue: 'am') as String;
  }
  
  static Future<void> setPhoneType(bool isSmartphone) async {
    final box = Hive.box(_settingsBox);
    await box.put('is_smartphone', isSmartphone);
  }
  
  static bool isSmartphone() {
    final box = Hive.box(_settingsBox);
    return box.get('is_smartphone', defaultValue: true) as bool;
  }

  // Pain Report operations
  static Future<void> savePainReport(PainReport report) async {
    final box = await Hive.openBox('pain_reports');
    await box.put(report.id, report.toJson());
  }

  static List<PainReport> getAllPainReports() {
    final box = Hive.box('pain_reports');
    return box.values
        .map((data) {
          try {
            return PainReport.fromJson(Map<String, dynamic>.from(data));
          } catch (e) {
            return null;
          }
        })
        .whereType<PainReport>()
        .toList();
  }

  // Feedback operations
  static Future<void> saveFeedback(efoy.Feedback feedback) async {
    final box = await Hive.openBox('feedback');
    await box.put(feedback.id, feedback.toJson());
  }

  static List<efoy.Feedback> getAllFeedback() {
    final box = Hive.box('feedback');
    return box.values
        .map((data) {
          try {
            return efoy.Feedback.fromJson(Map<String, dynamic>.from(data));
          } catch (e) {
            return null;
          }
        })
        .whereType<efoy.Feedback>()
        .toList();
  }
}

